name: Content Check

on:
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.mdx"
      - "source.config.ts"
      - "app/docs/**"
      - "lib/source.ts"
      - "mdx-components.tsx"
      - "package.json"
      - "pnpm-lock.yaml"
      - "next.config.mjs"
      - "postcss.config.mjs"
      - "tailwind.config.ts"
      - "tsconfig.json"

jobs:
  check-content:
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: "1"
      CI: "true"
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
      AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      # Non-blocking image migration + lint (visibility only)
      - name: Migrate images next to MDX (check only)
        run: pnpm migrate:images || echo "[warn] migrate:images failed (non-blocking)"

      - name: Lint image references (non-blocking)
        run: pnpm lint:images || echo "[warn] image lint found issues (non-blocking)"

      # Build the site to validate MDX and docs using Fumadocs
      - run: pnpm build
